# Generated by Django 4.2.4 on 2025-01-24 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='alice', max_length=30)),
                ('last_name', models.CharField(default='bob', max_length=30)),
                ('dob', models.DateField(null=True)),
            ],
        ),
    ]
